### ISSUE TITLE
Use of trademarked icon

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.ktechpit.whatsie#10]
@keshavbhatt Hello we are tracking a bunch of applications with trademark violations https://github.com/flathub/flathub/issues/5228.

The current icon is exactly a copy of the offcial WhatsaApp icon.

Please try to use your own icon for the application to avoid trademark issues and confusing people. I think 2 months is a reasonable time period for us to wait for the icon to be changed.

You can find some resources for icon guidelines in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon and name in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-name

And the guidelines on trademarks https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#no-trademark-violations

**Comment by bbhtt** [comment]
@keshavbhatt Any update? The two months is coming to an end..

**Comment by keshavbhatt** [comment]
@bbhtt i will make an update soon.

**Comment by keshavbhatt** [comment]
@bbhtt This issue should be fixed by https://github.com/flathub/com.ktechpit.whatsie/pull/11

**Comment by bbhtt** [comment]
@keshavbhatt thanks, can you please change it in the screenshots too?

**Comment by keshavbhatt** [comment]
@bbhtt I will update them soon.

**Comment by bbhtt** [comment]
@keshavbhatt any news on the screenshots ? It's a minor thing that is holding back. You can just take some new screenshots that shows the app window only.

**Comment by keshavbhatt** [comment]
@bbhtt will do it today, been busy with lots of things. 

Thanks for reminder.

**Comment by keshavbhatt** [comment]
new build contains updated screenshots.

**Comment by bbhtt** [comment]
Thank you!
